export default [
  { name: 'Bebida', cost: 30 },
  { name: 'Taco de birria', cost: 35 },
  { name: 'Media de birria', cost: 75 },
  { name: 'Orden de birria', cost: 100 },
  { name: 'Litro de birria', cost: 150 },
  { name: 'Taco de cabeza', cost: 35 },
  { name: 'Media de cabeza', cost: 75 },
  { name: 'Orden de cabeza', cost: 100 },
  { name: 'Litro de cabeza', cost: 150 },
  { name: 'Taco de lengua', cost: 100 },
  { name: 'Taco de chicharron', cost: 35 },
  { name: 'Taco Taimir', cost: 45 },
  { name: 'Quesabirrias de maiz', cost: 45 },
  { name: 'Quesabirrias de harina', cost: 50 },
  { name: 'Pellizcada', cost: 65 },
  { name: 'Asiento', cost: 15 },
  { name: 'Quesadilla', cost: 30 },
  { name: 'Tacos dorados', cost: 100 },
  { name: 'Gorditas', cost: 100 },
  { name: 'Tostadas', cost: 100 },
  { name: 'Desayuno', cost: 100 },
  { name: 'Mini Hot Cakes', cost: 45 },
  { name: 'Tortas', cost: 50 },
  { name: 'Cocido', cost: 100 },
  { name: 'Menudo Orden', cost: 100 },
  { name: 'Menudo Media', cost: 80 },
];
